import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI

# Load environment variables
load_dotenv()

# Get API key
google_api_key = os.getenv("GOOGLE_API_KEY")

# Initialize Gemma 3 27B Instruct
model = ChatGoogleGenerativeAI(
    model="gemma-3-27b-it",
    google_api_key=google_api_key,
    temperature=1.5, # Temperature is a parameter that controls the randomness of a language model's outputs. It affects how creative or deterministic the responses are. Lower values (0.0 - 0.3) mean more deterministic and predictable, whereas higher values (0.7-1.5) means more random, creative and diverse answer
    max_output_tokens=500, # When we are commnicating with a paid model, we need to pay for every generated output tokens. So we need to do so very carefully. We can think of it like number of words maximum that we want to be generated by our model
) 

# Invoke model
response = model.invoke("Write two or three lines about the history of Kolkata")
print(response.content)