import os
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
from langchain_groq import ChatGroq
from langchain_core.output_parsers import StrOutputParser
from langchain_core.runnables import RunnableSequence, RunnableParallel, RunnablePassthrough
# RunnablePassThrough is a special runnable primitive that simply returns the input as output wihout modifying it that is, as it is returns the same thing.
load_dotenv()

groq_api_key = os.getenv('GROQ_API_KEY')
model = ChatGroq(
    model="llama-3.1-8b-instant",
    groq_api_key=groq_api_key
)
parser = StrOutputParser()

template1 = PromptTemplate(
    template='Write a joke on {topic}',
    input_variables=['topic']
)

template2 = PromptTemplate(
    template="Explain the joke in simple words. Joke is \"{joke}\"",
    input_variables=['joke']
)

# As we noticed in runnable_sequence.py, the intermediate joke that was being generated by the model was not explicitly shown to us. We had to prompt the model explicitly with a format that we want like this (although no strict enforcement was there but it is solvable). To handle these types of scenarios, where we want the intermediate result as well as the final output, we use RunnablePassThrough. These can be useful in scenarios, where an intermediate result might become important in the later stages of the chain in raw form.
topic = input('Enter any topic: ')
joke_gen_chain = RunnableSequence(template1, model, parser)
joke_explain_with_orig_joke = RunnableParallel({
    'joke_explain': RunnableSequence(template2, model, parser),
    'original_joke': RunnablePassthrough()
})
final_chain = RunnableSequence(joke_gen_chain, joke_explain_with_orig_joke)
result = final_chain.invoke({'topic': topic})
print(f'Joke: {result['original_joke']}\n\n\nExplanation: {result['joke_explain']}')

final_chain.get_graph().draw_png('runnable_passthrough_chain.png')